baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[params]
    [params.dev]
        debug = true

[pagination]
    pagerSize = 4